### ISSUE TITLE
H2V on the same network

### ISSUE THREAD

**Issue by ghost** [FishPhd/H2V-Online-Launcher#26] opened 2016-06-13 03:36 UTC
I found out about the game project a few days ago and convinced my brother and dad to download the h2v launcher as well. After setting it up on all three computers (mine, my brothers, and my dads) I then proceeded to forward the UDP ports 1000-1006. The only issue is if one of us hosts a server, the others can't join the game, but it seems like others can. By the hosted server it shows a lock symbol but like I said others can join it. We can also join others peoples servers as well and play together. Is this an issue with the game limiting it to one PC per network or is it something else?

**Comment by pnill** [comment] 2016-06-13 05:36
The same issue with dedicated servers, you can't run one on the same network and join it.

It's a known limitation to the cartographer base at the moment and we're not sure when it will be fixed an option some have taken up who are running their own dedicated servers have started to use a VPN while playing on them.

Meaning if you host on one system the one that is not hosting would have to use a VPN in order to get into the game.

Come v0.2.1 things will be much different in terms of networking so maybe we'll see how things go then.

If you understood things from a networking/code level I'd certainly be willing to give a more in-depth explanation on the problem.

But for myself and Rude Yoshi (The other lead dev) we do not experience the issue, one thing I've noticed happening from debugging from some of those who do experience the issue is that it has to do with their router translating their WAN address into an internal one when the game attempts to send packets to it, it acts like a loop back for some odd reason rather then properly using NAT to send the packet to the appropriate host on the LAN.

**Comment by ghost** [comment] 2016-06-13 16:22
Where can I get a dedicated server for this or can you just use an old one? Would the server be only for people in the VPN like Hamachi? What VPNs would you recommend? I'm not big on programming knowledge only having little experience in BatariBasic and the slightest of HTML5 so I don't think the code would help me :) Thanks for the help.

**Comment by pnill** [comment] 2016-06-14 02:20
The dedicated server is irrelevant to the problem..... and currently we don't 'officially' support dedicated servers and won't until v0.2.1 is released.

Everyone who is not hosting would have to be using a VPN because it changes their WAN address, hopefully this problem is fixed in the next release as I said we're aware of the problem and it only affects specific network configurations.

**Comment by ghost** [comment] 2016-06-15 20:48
Alright, thanks for the help. One last question, is an in-game friends list planned for a future update? Thanks again.

**Closed as completed** 2016-08-18 18:51 UTC
